# Generated by Django 5.1 on 2024-08-17 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_id', models.IntegerField()),
                ('credit', models.DecimalField(decimal_places=3, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=2)),
                ('course_type', models.CharField(choices=[('AP', 'AP'), ('IB', 'IB'), ('DE', 'DE'), ('HN', 'HN'), ('POST', 'POST')], max_length=4)),
                ('course_offered', models.CharField(choices=[('ONLINE', 'Online'), ('ACADEMY', 'Academy'), ('CORE', 'Core')], max_length=7)),
                ('grades_list', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
