# Generated by Django 5.1 on 2024-08-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_coreq_ids_course_prereq_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coreq_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereq_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
